---
all:
  vars:
    ansible_user: vagrant
    system_supporters:
      - "vagrant"
  children:
    k3s:
      hosts:
        devstation:
          ansible_ssh_host: 172.17.177.11
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_ssh_private_key_file: /vagrant/local/.vagrant/machines/devstation/virtualbox/private_key
