---

- become: true
  pip:
    name: "{{ extra_pip_modules }}"
- include_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_theme: agnoster
    oh_my_zsh_plugins: "{{ zsh_plugins }}"
    users:
      - username: "{{ ansible_user }}"

- include_role:
    name: install_tool
  vars:
    tool_name: minioclient
    tool_version: mc.RELEASE.2020-01-13T22-49-03Z
    tool_download_sha256: 6e5af30404c2e1c9294899dc10094cfdf7e8d8f0a55e49707462a67749ae7828
    tool_downloadUrl: "https://dl.min.io/client/mc/release/linux-amd64/archive/{{ tool_version }}"
    tool_local_bin_name: mc
    tool_install_mode: direct

- include_role:
    name: install_tool
  vars:
    tool_name: kubectl
    tool_version: v1.17.0
    tool_download_sha256: 6e0aaaffe5507a44ec6b1b8a0fb585285813b78cc045f8804e70a6aac9d1cb4c
    tool_downloadUrl: https://storage.googleapis.com/kubernetes-release/release/{{ tool_version }}/bin/linux/amd64/kubectl
    tool_local_bin_name: kubectl
    tool_install_mode: direct

- include_role:
    name: install_tool
  vars:
    tool_name: helm
    tool_version: v3.0.2
    tool_download_sha256: c6b7aa7e4ffc66e8abb4be328f71d48c643cb8f398d95c74d075cfb348710e1d
    tool_downloadUrl: https://get.helm.sh/helm-{{ tool_version }}-linux-amd64.tar.gz
    tool_local_bin_name: helm
    tool_install_mode: archive
    tool_unarchive_extra_opts: [--strip-components=1]

- include_role:
    name: install_tool
  vars:
    tool_name: vault
    tool_version: 1.3.1
    tool_download_sha256: b49de8fd508eb9c2c222fa0f38e23546fb28991af2e8bfdb9bbe381a380f9baa
    tool_downloadUrl: https://releases.hashicorp.com/vault/{{ tool_version }}/vault_{{ tool_version }}_linux_amd64.zip
    tool_local_bin_name: vault
    tool_install_mode: archive

- include_role:
    name: install_tool
  vars:
    tool_name: terraform
    tool_version: 0.12.19
    tool_download_sha256: a549486112f5350075fb540cfd873deb970a9baf8a028a86ee7b4472fc91e167
    tool_downloadUrl: https://releases.hashicorp.com/terraform/{{ tool_version }}/terraform_{{ tool_version }}_linux_amd64.zip
    tool_local_bin_name: terraform
    tool_install_mode: archive

- include_role:
    name: install_tool
  vars:
    tool_name: velero
    tool_version: v1.2.0
    tool_download_sha256: 4080a37b487a859b5bba8391e965267cd0fe29cd67fd070b6f695fed45619e2c
    tool_downloadUrl: https://github.com/vmware-tanzu/velero/releases/download/{{ tool_version }}/velero-{{ tool_version }}-darwin-amd64.tar.gz
    tool_local_bin_name: velero
    tool_install_mode: archive
    tool_unarchive_extra_opts: [--strip-components=1]
